---
title: "Gerrymandering Notebook"
output: html_notebook
---

```{r}
library(sf)          # classes and functions for vector data
library(spData)        # load geographic data
library(dplyr)
library(tmap)    # for static and interactive maps
library(ggplot2) 
library(ggsci)
library(tools)
library(readr)

library(foreach)
library(doParallel)

registerDoParallel(detectCores())
getDoParWorkers()
```


```{r,fig.width=10,fig.height=5}
vis=function(state){
  #state='al'
  load(paste("data/",state,".data.RData",sep=''))
  datset=paste(state,".data",sep='')
  dem=tm_shape(noquote(datset)) +tm_fill(col = "dist",palette = "viridis",legend.show=FALSE,alpha=0.4)+tm_dots(size = "party_dem",col="blue",alpha=0.5,legend.show=FALSE)+tm_layout(title = state, frame = FALSE, bg.color = NA)
  rep=tm_shape(noquote(datset)) +tm_fill(col = "dist",palette = "viridis",legend.show=FALSE,alpha=0.4)+tm_dots(size = "party_rep",col="red",alpha=0.5,legend.show=FALSE)+tm_layout(title = '', frame = FALSE, bg.color = NA)
  black=tm_shape(noquote(datset)) +tm_fill(col = "dist",palette = "viridis",legend.show=FALSE,alpha=0.4)+tm_dots(size = "eth1_aa",col="black",alpha=0.5,legend.show=FALSE)+ tm_layout(title = "", frame = FALSE, bg.color = NA)
  white=tm_shape(noquote(datset)) +tm_fill(col = "dist",palette = "viridis",legend.show=FALSE,alpha=0.4)+tm_dots(size = "eth1_eur",col="yellow",alpha=0.5,legend.show=FALSE)+tm_layout(title = "", frame = FALSE, bg.color = NA)
  hisp=tm_shape(noquote(datset)) +tm_fill(col = "dist",palette = "viridis",legend.show=FALSE,alpha=0.4)+tm_dots(size = "eth1_hisp",col="brown",alpha=0.5,legend.show=FALSE)+tm_layout(title = "", frame = FALSE, bg.color = NA)
  asian=tm_shape(noquote(datset)) +tm_fill(col = "dist",palette = "viridis",legend.show=FALSE,alpha=0.4)+tm_dots(size = "eth1_esa",col="orange",alpha=0.5,legend.show=FALSE)+tm_layout(title = "", frame = FALSE, bg.color = NA)
  p=tmap_arrange(black,white,hisp,asian,dem,rep,
             nrow = 2,ncol=4)
return(p)

  
}
state1=substr(list.files("/home/zhoux104/R/Gerry/congressional2010"),1,2)
state2=substr(list.files("/home/zhoux104/R/Gerry/block2010"),1,2)
state3=tolower(substr(list.files("/home/zhoux104/R/Gerry/voter2021"),1,2))
states=intersect(intersect(state1,state2),state3)

for(s in 1:length(states)){
  s=1
  if(states[s]!='co' & states[s]!='fl'){
    p=vis(states[s])
    print(p)
  }
  
}


load("data/ca.data.RData")
dem=tm_shape(ca.data) +tm_fill(col = "dist",palette = "viridis",legend.show=FALSE,alpha=0.4)+
  tm_dots(size = "party_dem",col="blue",alpha=0.5,legend.show=FALSE)+
  tm_layout(title = "California", frame = FALSE, bg.color = NA)
rep=tm_shape(ca.data) +tm_fill(col = "dist",palette = "viridis",legend.show=FALSE,alpha=0.4)+
  tm_dots(size = "party_rep",col="red",alpha=0.5,legend.show=FALSE)+
  tm_layout(title = "California", frame = FALSE, bg.color = NA)
black=tm_shape(ca.data) +tm_fill(col = "dist",palette = "viridis",legend.show=FALSE,alpha=0.4)+
  tm_dots(size = "eth1_aa",col="black",alpha=0.5,legend.show=FALSE)+
  tm_layout(title = "California", frame = FALSE, bg.color = NA)
white=tm_shape(ca.data) +tm_fill(col = "dist",palette = "viridis",legend.show=FALSE,alpha=0.4)+
  tm_dots(size = "eth1_eur",col="yellow",alpha=0.5,legend.show=FALSE)+
  tm_layout(title = "California", frame = FALSE, bg.color = NA)
hisp=tm_shape(ca.data) +tm_fill(col = "dist",palette = "viridis",legend.show=FALSE,alpha=0.4)+tm_dots(size = "eth1_hisp",col="brown",alpha=0.5,legend.show=FALSE)+tm_layout(title = "California", frame = FALSE, bg.color = NA)
asian=tm_shape(ca.data) +tm_fill(col = "dist",palette = "viridis",legend.show=FALSE,alpha=0.4)+tm_dots(size = "eth1_esa",col="orange",alpha=0.5,legend.show=FALSE)+tm_layout(title = "California", frame = FALSE, bg.color = NA)


tmap_arrange(black,white,hisp,asian,dem,rep,nrow = 2,ncol=4)

 
```

```{r,fig.width=10,fig.height=5}
load("data/tx.data.RData")
dem=tm_shape(tx.data) +tm_fill(col = "dist",palette = "viridis",legend.show=FALSE,alpha=0.4)+
  tm_dots(size = "party_dem",col="blue",alpha=0.5,legend.show=FALSE)+
  tm_layout(title = "Texas", frame = FALSE, bg.color = NA)
rep=tm_shape(tx.data) +tm_fill(col = "dist",palette = "viridis",legend.show=FALSE,alpha=0.4)+
  tm_dots(size = "party_rep",col="red",alpha=0.5,legend.show=FALSE)+
  tm_layout(title = "Texas", frame = FALSE, bg.color = NA)
black=tm_shape(tx.data) +tm_fill(col = "dist",palette = "viridis",legend.show=FALSE,alpha=0.4)+
  tm_dots(size = "eth1_aa",col="black",alpha=0.5,legend.show=FALSE)+
  tm_layout(title = "Texas", frame = FALSE, bg.color = NA)
white=tm_shape(tx.data) +tm_fill(col = "dist",palette = "viridis",legend.show=FALSE,alpha=0.4)+
  tm_dots(size = "eth1_eur",col="yellow",alpha=0.5,legend.show=FALSE)+
  tm_layout(title = "Texas", frame = FALSE, bg.color = NA)
hisp=tm_shape(tx.data) +tm_fill(col = "dist",palette = "viridis",legend.show=FALSE,alpha=0.4)+tm_dots(size = "eth1_hisp",col="brown",alpha=0.5,legend.show=FALSE)+tm_layout(title = "Texas", frame = FALSE, bg.color = NA)
asian=tm_shape(tx.data) +tm_fill(col = "dist",palette = "viridis",legend.show=FALSE,alpha=0.4)+tm_dots(size = "eth1_esa",col="orange",alpha=0.5,legend.show=FALSE)+tm_layout(title = "Texas", frame = FALSE, bg.color = NA)


tmap_arrange(black,white,hisp,asian,dem,rep,nrow = 2,ncol=4)
 
```




```{r}
library(ggplot2)
library(dplyr)
library(ggsci)
library(qte)
library(CVXR)
```


```{r,fig.width=8,fig.height=5}

load("data/power.data.RData")

###### My own Quantile treatment effect model


quantile=function(taus, y, wt){
 
  # minimize sum of check functions
  
  q <- Variable(1)
  quant_loss <- function(u, tau) { 0.5 * abs(u) + (tau - 0.5) * u }
  solutions <- sapply(taus, function(tau) {
    obj <- sum(wt*quant_loss(y-q,tau))
    prob <- Problem(Minimize(obj))
    ## THE OSQP solver returns an error for tau = 0.5
    solve(prob, solver = "ECOS")$getValue(q)
  })
  return(solutions)
}

QTE=function(dataset, taus){
  
  
  #pscore.reg <- glm(T ~ , data=dataset, family=binomial)
  #pscore <- fitted(pscore.reg)
  
  q.trt=quantile(taus=taus, y=dataset$Y, wt=dataset$T*dataset$eth1_hisp)
  q.control=quantile(taus=taus, y=dataset$Y, wt=(1-dataset$T)*dataset$eth1_hisp)
  return(q.trt-q.control)
  
}

#unique(power.data$STATE)
power.data%>%
  mutate(black.power=black.power*100,
         white.power=white.power*100,
         hisp.power=hisp.power*100,
         asian.power=asian.power*100)%>%
  mutate(A=ifelse(STATE %in% c("Arizona","California","Hawaii","Idaho","Montana","New Jersey","Washington","Alaska","Arkansas","Colorado","Missouri","Ohio","Pennsylvania","Iowa"),
                  "Nonpartisan or bipartisan commissions",
                  ifelse(STATE %in% c("Delaware","Illinois","Maryland","Massachusetts","Nevada","New Mexico","New York","Oregon","Rhode Island"),
                         "Democratic",
                         ifelse(STATE %in% c("Alabama","Florida","Georgia","Indiana","Kansas","Kentucky","Mississippi","New Hampshire","North Carolina","North Dakota","Oklahoma","South Carolina","South Dakota","Tennessee","Texas","Utah","West Virginia","Wyoming"),"Republican",""))))%>%filter(A !="")%>%
  ggplot()+
  geom_density(aes(x=white.power,y=..scaled..,weight=eth1_eur,group=A,col=A))+
  scale_color_startrek()+
  ggtitle("White voter power")

power.data%>%
  mutate(black.power=black.power*100,
         white.power=white.power*100,
         hisp.power=hisp.power*100,
         asian.power=asian.power*100)%>%
  mutate(A=ifelse(STATE %in% c("Arizona","California","Hawaii","Idaho","Montana","New Jersey","Washington","Alaska","Arkansas","Colorado","Missouri","Ohio","Pennsylvania","Iowa"),
                  "Nonpartisan or bipartisan commissions",
                  ifelse(STATE %in% c("Delaware","Illinois","Maryland","Massachusetts","Nevada","New Mexico","New York","Oregon","Rhode Island"),
                         "Democratic",
                         ifelse(STATE %in% c("Alabama","Florida","Georgia","Indiana","Kansas","Kentucky","Mississippi","New Hampshire","North Carolina","North Dakota","Oklahoma","South Carolina","South Dakota","Tennessee","Texas","Utah","West Virginia","Wyoming"),"Republican",""))))%>%filter(A !="")%>%
  ggplot()+
  geom_density(alpha=0.1,aes(x=black.power,y=..scaled..,weight=eth1_aa,group=A,col=A))+scale_color_startrek()+
  ggtitle("Black voter power")
 
power.data%>%
  mutate(black.power=black.power*100,
         white.power=white.power*100,
         hisp.power=hisp.power*100,
         asian.power=asian.power*100)%>%
  mutate(A=ifelse(STATE %in% c("Arizona","California","Hawaii","Idaho","Montana","New Jersey","Washington","Alaska","Arkansas","Colorado","Missouri","Ohio","Pennsylvania","Iowa"),
                  "Nonpartisan or bipartisan commissions",
                  ifelse(STATE %in% c("Delaware","Illinois","Maryland","Massachusetts","Nevada","New Mexico","New York","Oregon","Rhode Island"),
                         "Democratic",
                         ifelse(STATE %in% c("Alabama","Florida","Georgia","Indiana","Kansas","Kentucky","Mississippi","New Hampshire","North Carolina","North Dakota","Oklahoma","South Carolina","South Dakota","Tennessee","Texas","Utah","West Virginia","Wyoming"),"Republican",""))))%>%filter(A !="")%>%
  ggplot()+
  geom_density(alpha=0.1,aes(x=hisp.power,y=..scaled..,weight=eth1_hisp,group=A,col=A))+scale_color_startrek()+
  ggtitle("Hisp voter power")


power.data%>%
  mutate(black.power=black.power*100,
         white.power=white.power*100,
         hisp.power=hisp.power*100,
         asian.power=asian.power*100)%>%
  mutate(A=ifelse(STATE %in% c("Arizona","California","Hawaii","Idaho","Montana","New Jersey","Washington","Alaska","Arkansas","Colorado","Missouri","Ohio","Pennsylvania","Iowa"),
                  "Nonpartisan or bipartisan commissions",
                  ifelse(STATE %in% c("Delaware","Illinois","Maryland","Massachusetts","Nevada","New Mexico","New York","Oregon","Rhode Island"),
                         "Democratic",
                         ifelse(STATE %in% c("Alabama","Florida","Georgia","Indiana","Kansas","Kentucky","Mississippi","New Hampshire","North Carolina","North Dakota","Oklahoma","South Carolina","South Dakota","Tennessee","Texas","Utah","West Virginia","Wyoming"),"Republican",""))))%>%filter(A !="")%>%
  ggplot()+
  geom_density(alpha=0.1,aes(x=asian.power,y=..scaled..,weight=eth1_esa,group=A,col=A))+scale_color_startrek()+
  ggtitle("Asian voter power")
 
#table(power.data$STATE,power.data$A)
```


```{r}
#unique(power.data$STATE)
power.data=power.data%>%
  mutate(black.power=black.power*100,
         white.power=white.power*100,
         hisp.power=hisp.power*100,
         asian.power=asian.power*100)%>%
  mutate(A=ifelse(STATE %in% c("Arizona","California","Hawaii","Idaho","Montana","New Jersey","Washington","Alaska","Arkansas","Colorado","Missouri","Ohio","Pennsylvania","Iowa"),
                  "Nonpartisan or bipartisan commissions",
                  ifelse(STATE %in% c("Delaware","Illinois","Maryland","Massachusetts","Nevada","New Mexico","New York","Oregon","Rhode Island"),
                         "Democratic",
                         ifelse(STATE %in% c("Alabama","Florida","Georgia","Indiana","Kansas","Kentucky","Mississippi","New Hampshire","North Carolina","North Dakota","Oklahoma","South Carolina","South Dakota","Tennessee","Texas","Utah","West Virginia","Wyoming"),"Republican",""))))%>%
  filter(A %in% c("Republican","Nonpartisan or bipartisan commissions"))%>%mutate(T=ifelse(A=="Republican",1,0))
#table(power.data$STATE,power.data$A)

taus=c(0.05,0.1, 0.25, 0.5, 0.75, 0.90, 0.95)
q.trt=quantile(taus=taus, y=power.data$black.power, wt=power.data$T*power.data$eth1_aa)
q.control=quantile(taus=taus, y=power.data$black.power, wt=(1-power.data$T)*power.data$eth1_aa)
black.qte=q.trt-q.control
#plot(c(0.05,0.1, 0.25, 0.5, 0.75, 0.90, 0.95),black.qte,type="b")

q.trt=quantile(taus=taus, y=power.data$white.power, wt=power.data$T*power.data$eth1_eur)
q.control=quantile(taus=taus, y=power.data$white.power, wt=(1-power.data$T)*power.data$eth1_eur)
white.qte=q.trt-q.control
#plot(c(0.05,0.1, 0.25, 0.5, 0.75, 0.90, 0.95),white.qte,type="b")

q.trt=quantile(taus=taus, y=power.data$hisp.power, wt=power.data$T*power.data$eth1_hisp)
q.control=quantile(taus=taus, y=power.data$hisp.power, wt=(1-power.data$T)*power.data$eth1_hisp)
hisp.qte=q.trt-q.control
#plot(c(0.05,0.1, 0.25, 0.5, 0.75, 0.90, 0.95),hisp.qte,type="b")


q.trt=quantile(taus=taus, y=power.data$asian.power, wt=power.data$T*power.data$eth1_esa)
q.control=quantile(taus=taus, y=power.data$asian.power, wt=(1-power.data$T)*power.data$eth1_esa)
asian.qte=q.trt-q.control
#plot(c(0.05,0.1, 0.25, 0.5, 0.75, 0.90, 0.95),asian.qte,type="b")

data.frame(q=rep(c(0.05,0.1, 0.25, 0.5, 0.75, 0.90, 0.95),4),qte=c(black.qte,white.qte,hisp.qte,asian.qte),race=rep(c("Black","White","Hispanic","Asian"),each=7))%>%
  ggplot(aes(x=q,y=qte,col=race))+
  geom_point()+
  geom_line()+
  scale_color_startrek()

```

